modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/Mos-Origins/GroundedOrigins/issues" 
[[mods]]
modId="grounded_origins"
version="${file.jarVersion}"
displayName="Grounded Origins"
displayURL="https://www.curseforge.com/members/mo_shark/projects"
logoFile="icon.png"
credits="Much love to the Origins discord."
authors="mo_shark/momo, pachiremi"
description='''
An Origins addon that adds the Beach Crab, Deer, Moth, and Penguin origins.
'''
# Forge
[[dependencies.grounded_origins]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.32,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.grounded_origins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

# Origins Forge
[[dependencies.grounded_origins]]
    modId="origins"
    mandatory=true
    versionRange="[0.7.3.9,)"
    ordering="NONE"
    side="BOTH"

# Origins Power Extension
[[dependencies.grounded_origins]]
    modId="origins_power_expansion"
    mandatory=true
    versionRange="[1.5.0,)"
    ordering="NONE"
    side="BOTH"

# Pehkui
[[dependencies.grounded_origins]]
    modId="pehkui"
    mandatory=true
    versionRange="[3.1.0,)"
    ordering="NONE"
    side="BOTH"
