modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/Mos-Origins/GroundedOrigins/issues" 
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/grounded-origins"
logoFile="icon.png"
authors="mo_shark/momo, pachiremi"
description='''${mod_description}'''
# Forge
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"

# Origins Forge
[[dependencies.${mod_id}]]
    modId="origins"
    mandatory=true
    versionRange="[1.3,)"
    ordering="NONE"
    side="BOTH"

# Pehkui
[[dependencies.${mod_id}]]
    modId="pehkui"
    mandatory=true
    versionRange="[3.1.0]"
    ordering="NONE"
    side="BOTH"
